spring:
  profiles.active: development

---
spring:
  profiles: development
  mvc:  
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      url: jdbc:mariadb://here-my-posts-db.czllu3jioidj.ap-northeast-2.rds.amazonaws.com:3306/here_my_posts_db
      username: here_my_posts_app
      password: abc123!
      driver-class-name: org.mariadb.jdbc.Driver
      driverClassName: org.mariadb.jdbc.Driver
      tomcat:
        min-idle: 5
#       initial-size: 5 
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
#   password: gksdkfkd123
    port: 6379
logging:
  level:
    org:
      springframework:
        web: DEBUG
