spring:
  profiles.active: development

---
spring:
  profiles: development
  mvc:  
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      url: jdbc:mariadb://localhost:3306/hsblog
      username: hsblogdb
      password: hsblogdb123
      driver-class-name: org.mariadb.jdbc.Driver
      driverClassName: org.mariadb.jdbc.Driver
      tomcat:
        min-idle: 5
#       initial-size: 5 
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
#   password: gksdkfkd123
    port: 6379
logging:
  level:
    org:
      springframework:
        web: DEBUG
